apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-deploy
  template:
    metadata:
      labels:
        app: simple-deploy
    spec:
      containers:
        - image: abc
          name: nginx
          ports:
            - containerPort: 80
